// examples/react/src/About.tsx
import { Suspense } from "react";
import { Link } from "react-router-dom";

import { AsyncData } from "./AsyncData.jsx";

export function About() {
  return (
    <main>
      <h1>
        This page is completely static. Async data:{" "}
        <Suspense fallback={<span> loading...</span>}>
          <AsyncData />
        </Suspense>
      </h1>
      <section>
        An since it does not contain any interactive islands, no JavaScript is
        shipped to the browser.
      </section>
      <Link to="/">Home</Link>
    </main>
  );
}

// examples/vue/src/About.vue
<script setup lang="ts">
import AsyncData from "./AsyncData.vue";
</script>
<template>
  <main>
    <h1>This page is completely static.</h1>
    <section>
      An since it does not contain any interactive islands, no JavaScript is
      shipped to the browser. Async data:
      <Suspense>
        <template #fallback><span>Loading...</span></template>
        <AsyncData />
      </Suspense>
    </section>
    <router-link to="/">Home</router-link>
  </main>
</template>
