// examples/vercel/src/Counter.island.tsx
import { useState } from "react";

type Props = {
  start?: number;
};

export default function Counter({ start = 0 }: Props) {
  const [counter, setCounter] = useState(start);
  return (
    <div className="counter" data-testid="counter">
      <button onClick={() => setCounter((c) => c - 1)}>-</button>
      <span>{counter}</span>
      <button onClick={() => setCounter((c) => c + 1)}>+</button>
    </div>
  );
}

// examples/vue/src/Counter.island.vue
<script setup lang="ts">
import { ref } from "vue";

interface Props {
  start?: number;
}
const { start = 0 } = defineProps<Props>();
const count = ref(start);
</script>

<template>
  <div data-testid="counter">
    <button @click="count--">-</button>
    <span>{{ count }}</span>
    <button @click="count++">+</button>
  </div>
</template>

<style scoped>
div {
  display: inline-flex;
  gap: 0.5em;
}
</style>
