// examples/svelte/src/Home.svelte
<script>
  import CounterIsland from "./Counter.island.svelte";
  import { RouterLink } from "svelte-pilot";
  import ExpandableIsland from "./Expandable.island.svelte";
  import MediaQueryIsland from "./MediaQuery.island.svelte";
  import ServerContent from "./ServerContent.svelte";
</script>

<main>
  <h1>
    Partial hydration with Svelte and <i>Capri</i>
  </h1>
  <section>This page is static, but contains some dynamic parts.</section>
  <section>
    Here is a simple counter: <CounterIsland />
  </section>
  <section>
    And here is another one, independent from the one above: <CounterIsland
      counter={100}
    />
  </section>
  <ExpandableIsland>
    <span slot="title">Click to expand</span>
    <div slot="body">
      <ServerContent>
        The code for <code>ServerContent</code> won't show up in the client bundle.
      </ServerContent>
    </div>
  </ExpandableIsland>
  <MediaQueryIsland />
  <RouterLink to="about">Link to another page</RouterLink>
</main>

// examples/vue/src/Home.vue
<script setup lang="ts">
import CounterIsland from "./Counter.island.vue";
import ExpandableIsland from "./Expandable.island.vue";
import MediaQueryIsland from "./MediaQuery.island.vue";
import ServerContent from "./ServerContent.vue";
</script>
<template>
  <main>
    <h1>Partial hydration with Vue and <i>Capri</i></h1>
    <section>This page is static, but contains some dynamic parts.</section>
    <section>Here is a simple counter: <CounterIsland /></section>
    <section>
      And here is another one, independent from the one above:
      <CounterIsland :start="100" />
    </section>
    <ExpandableIsland>
      <template #title>Click to expand</template>
      <template #body>
        <ServerContent>
          The code for <code>ServerContent</code> won't show up in the client
          bundle.
        </ServerContent>
      </template>
    </ExpandableIsland>
    <MediaQueryIsland />
    <router-link to="/about">Another page</router-link>
  </main>
</template>
