// examples/cloudflare/src/MediaQuery.island.tsx
import { useEffect, useState } from "react";

export const options = {
  media: "(max-width:500px)",
};

export default function MediaQuery() {
  const [content, setContent] = useState(
    "Resize your browser below 500px to hydrate this island.",
  );
  useEffect(() => {
    setContent("The island has been hydrated.");
  }, []);
  return <div className="box">{content}</div>;
}

// examples/vue/src/MediaQuery.island.vue
<script lang="ts">
export const options = {
  media: "(max-width:500px)",
};
</script>

<script setup lang="ts">
import { ref, onMounted } from "vue";

const content = ref("Resize your browser below 500px to hydrate this island.");

onMounted(() => {
  content.value = "The island has been hydrated.";
});
</script>

<template>
  <div class="box">{{ content }}</div>
</template>
