// examples/svelte/src/MediaQuery.island.svelte
<script context="module">
  export const options = {
    media: "(max-width:500px)",
  };
</script>

<script>
  import { onMount } from "svelte";
  let content = "Resize your browser below 500px to hydrate this island.";
  onMount(() => {
    content = "The island has been hydrated.";
  });
</script>

<div class="box">
  {content}
</div>

// examples/cloudflare/src/MediaQuery.island.tsx
import { useEffect, useState } from "react";

export const options = {
  media: "(max-width:500px)",
};

export default function MediaQuery() {
  const [content, setContent] = useState(
    "Resize your browser below 500px to hydrate this island.",
  );
  useEffect(() => {
    setContent("The island has been hydrated.");
  }, []);
  return <div className="box">{content}</div>;
}
