// examples/solid/src/Counter.island.tsx
import { createSignal } from "solid-js";
import { island } from "virtual:island";

type Props = {
  start?: number;
};

export function Counter({ start = 0 }: Props) {
  const [counter, setCounter] = createSignal(start);
  return (
    <div data-testid="counter">
      <button onClick={() => setCounter((c) => c - 1)}>-</button>
      <span>{counter()}</span>
      <button onClick={() => setCounter((c) => c + 1)}>+</button>
    </div>
  );
}

export const CounterIsland = island(Counter);

// examples/preact/src/Counter.island.tsx
import { useState } from "preact/hooks";
import { island } from "virtual:island";

export function Counter({ start = 0 }: { start?: number }) {
  const [counter, setCounter] = useState(start);
  return (
    <div class="counter" data-testid="counter">
      <button onClick={() => setCounter((c) => c - 1)}>-</button>
      {counter}
      <button onClick={() => setCounter((c) => c + 1)}>+</button>
    </div>
  );
}

export const CounterIsland = island(Counter);
