// examples/solid/src/main.server.tsx
import { RenderFunction, renderToString } from "@capri-js/solid/server";
import { Router } from "solid-app-router";
import { generateHydrationScript } from "solid-js/web";

import { App } from "./App";

export const render: RenderFunction = async (url: string) => {
  const html = await renderToString(() => (
    <Router base={import.meta.env.BASE_URL} url={url}>
      <App />
    </Router>
  ));
  return {
    "#app": html,
    body: generateHydrationScript(),
  };
};

// examples/vercel/src/main.server.tsx
import { RenderFunction, renderToString } from "@capri-js/react/server";
import { StrictMode } from "react";
import { StaticRouter } from "react-router-dom/server.js";

import { App } from "./App";

export const render: RenderFunction = async (url, context) => {
  context.setHeader("Cache-Control", "s-maxage=60, stale-while-revalidate=60");
  return {
    "#app": await renderToString(
      <StrictMode>
        <StaticRouter location={url} basename={import.meta.env.BASE_URL}>
          <App />
        </StaticRouter>
      </StrictMode>,
    ),
  };
};
