// examples/svelte/src/App.svelte
<script>
  import { Router, Route } from "svelte-navigator";
  import Home from "./Home.svelte";
  import About from "./About.svelte";
  import "./global.css";
  // Used for SSR. A falsy value is ignored by the Router.
  export let url = "";
</script>

<Router {url}>
  <Route path="/" component={Home} />
  <Route path="about" component={About} />
</Router>

// examples/solid/src/App.tsx
import "./App.css";

import { Route, Routes } from "solid-app-router";

import { About } from "./About";
import { Home } from "./Home";

export function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="/about" element={<About />} />
    </Routes>
  );
}
