// examples/react/src/App.tsx
import "./App.css";

import { Suspense } from "react";
import { Route, Routes } from "react-router-dom";

import { About } from "./About";
import { Home } from "./Home";

export function App() {
  return (
    <Suspense>
      <Routes>
        <Route index element={<Home />} />
        <Route path="/about" element={<About />} />
      </Routes>
    </Suspense>
  );
}

// examples/solid/src/App.tsx
import "./App.css";

import { Route, Routes } from "solid-app-router";
import { NoHydration } from "solid-js/web";

import { About } from "./About";
import { Home } from "./Home";

export function App() {
  return (
    <NoHydration>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/about" element={<About />} />
      </Routes>
    </NoHydration>
  );
}
