// examples/preact/src/MediaQuery.island.tsx
import { useEffect, useState } from "preact/hooks";

export const options = {
  media: "(max-width:500px)",
};

export default function MediaQuery() {
  const [content, setContent] = useState(
    "Resize your browser below 500px to hydrate this island."
  );
  useEffect(() => {
    setContent("The island has been hydrated.");
  }, []);
  return <div className="box">{content}</div>;
}

// examples/solid/src/MediaQuery.island.tsx
import { createSignal, onMount } from "solid-js";

export const options = {
  media: "(max-width:500px)",
};

export default function MediaQuery() {
  const [content, setContent] = createSignal(
    "Resize your browser below 500px to hydrate this island."
  );
  onMount(() => {
    setContent("The island has been hydrated.");
  });
  return <div class="box">{content}</div>;
}
