// packages/solid/src/hydrate.tsx
import { HydrationAdapter } from "capri/vite-plugin";
import { hydrate as solidHydrate } from "solid-js/web";

const adapter: HydrationAdapter = {
  hydrate(component, props, element) {
    const key = element.getAttribute("data-hk");
    if (!key) {
      throw new Error("Can't hydrate an element without a data-hk attribute.");
    }
    const renderId = key.slice(0, -1);
    solidHydrate(() => component(props), element.parentElement!, { renderId });
  },

  renderChildren() {
    return <capri-children style={{ display: "contents" }} innerHTML="" />;
  },
};

export default adapter;

// packages/react/src/hydrate.ts
import { HydrationAdapter } from "capri/vite-plugin";
import { ComponentType, createElement } from "react";
import { hydrateRoot } from "react-dom/client";

const adapter: HydrationAdapter = {
  hydrate(component: ComponentType, props: object, element: Element) {
    return hydrateRoot(element.parentElement!, createElement(component, props));
  },

  renderChildren() {
    return createElement("capri-children", {
      style: { display: "contents" },
      dangerouslySetInnerHTML: { __html: "" },
    });
  },
};

export default adapter;
