// packages/solid/src/renderMarkerFragment.jsx
import { NoHydration } from "solid-js/web";

export function renderMarkerFragment(
  Component,
  props,
  scriptProps,
  scriptContent
) {
  return (
    <>
      <Component {...props} />
      <NoHydration>
        <script {...scriptProps} innerHTML={scriptContent} />
      </NoHydration>
    </>
  );
}

// packages/react/src/renderMarkerFragment.tsx
import { ComponentType } from "react";

export function renderMarkerFragment(
  Component: ComponentType,
  props: object,
  scriptProps: object,
  scriptContent: string
) {
  return (
    <>
      <Component {...props} />
      <script
        {...scriptProps}
        dangerouslySetInnerHTML={{ __html: scriptContent }}
      />
    </>
  );
}
