// packages/solid/src/server.tsx
import {
  createIslandComponent,
  IslandOptions,
  RenderFunction,
  RenderResult,
} from "capri";
import { sharedConfig } from "solid-js";
import { NoHydration } from "solid-js/web";

export type { RenderFunction, RenderResult };

import plugin from "./plugin.js";

export default plugin;

export function Hydration(props: any) {
  const c: any = sharedConfig.context;
  c.noHydrate = false;
  const children = props.children;
  c.noHydrate = true;
  return children;
}

export function island<T extends (props: any) => any>(
  Component: T,
  options: IslandOptions = {}
) {
  return createIslandComponent(
    Component,
    options,
    ({ props, children, scriptProps, scriptContent }) => {
      const wrappedChildren = children && <NoHydration>{children}</NoHydration>;
      return (
        <div data-island-root style="display: contents">
          <Hydration>
            <Component {...props}>{wrappedChildren}</Component>
          </Hydration>
          <script {...scriptProps} innerHTML={scriptContent} />
        </div>
      );
    }
  );
}

// packages/react/src/server.ts
import { createIslandComponent, IslandOptions } from "capri";
import { ComponentType, createElement } from "react";

export function island<T extends ComponentType<any>>(
  component: T,
  options: IslandOptions = {}
) {
  return createIslandComponent(
    component,
    options,
    ({ props, children, scriptProps, scriptContent }) => {
      const wrappedChildren =
        children &&
        createElement("div", { "data-island-children": true }, children);

      return createElement(
        "div",
        { "data-island-root": true, style: { display: "contents" } },
        createElement(component, props, wrappedChildren),
        createElement("script", {
          ...scriptProps,
          dangerouslySetInnerHTML: { __html: scriptContent },
        })
      );
    }
  );
}
