// packages/react/src/browser.ts
import { IslandOptions } from "capri";
import { ComponentType } from "react";

export function island<T extends ComponentType<any>>(
  component: T,
  options: IslandOptions = {}
) {
  // In the browser this island function is a no-op and returns the passed
  // component verbatim.
  return component;
}

// packages/solid/src/browser.tsx
import { Component } from "solid-js";

export function island<T extends Component<any>>(component: T, options = {}) {
  // In the browser this island function is a no-op and returns the passed
  // component verbatim.
  return component;
}

export function lagoon<T extends Component<any>>(
  factory: () => Promise<{ default: T }>
) {
  return (props: any) => {
    return <capri-lagoon innerHTML="" />;
  };
}
