// packages/react/src/index.ts
import { createIslandComponent, IslandOptions } from "capri";
import React, { ComponentType, createElement } from "react";
import renderToString from "react-render-to-string";

export type { RenderFunction } from "capri";
export { renderToString };

export function island<T extends ComponentType<any>>(
  component: T,
  options: IslandOptions = {}
) {
  return createIslandComponent(
    component,
    options,
    ({ props, children, scriptProps, scriptContent }) => {
      const wrappedChildren =
        children &&
        createElement(
          "capri-children",
          { style: { display: "contents" } },
          children
        );

      return createElement(
        "capri-island",
        { style: { display: "contents" } },
        createElement(component, props, wrappedChildren),
        createElement("script", {
          ...scriptProps,
          dangerouslySetInnerHTML: { __html: scriptContent },
        })
      );
    }
  );
}

export function lagoon<T extends ComponentType<any>>(
  factory: () => Promise<{ default: T }>
) {
  const Comp = React.lazy(factory);
  return (props: any) => {
    return createElement(
      "capri-lagoon",
      { style: { display: "contents" } },
      createElement(Comp, props)
    );
  };
}

// packages/solid/src/index.tsx
import { createIslandComponent, IslandOptions } from "capri";
import { Component, ComponentProps, lazy, sharedConfig } from "solid-js";
import { NoHydration } from "solid-js/web";

import plugin from "./vite-plugin.js";

export default plugin;

export function Hydration(props: any) {
  const c: any = sharedConfig.context;
  c.noHydrate = false;
  const children = props.children;
  c.noHydrate = true;
  return children;
}
export type { RenderFunction } from "capri";
export { renderToStringAsync as renderToString } from "solid-js/web";

export function island<T extends (props: any) => any>(
  Component: T,
  options: IslandOptions = {}
) {
  return createIslandComponent(
    Component,
    options,
    ({ props, children, scriptProps, scriptContent }) => {
      const wrappedChildren = children && <NoHydration>{children}</NoHydration>;

      return (
        <capri-island style="display: contents">
          <Hydration>
            <Component {...props}>{wrappedChildren}</Component>
          </Hydration>
          <script {...scriptProps} innerHTML={scriptContent} />
        </capri-island>
      );
    }
  );
}

export function lagoon<T extends Component<any>>(
  factory: () => Promise<{ default: T }>
) {
  const Comp = lazy(factory);
  return (props: ComponentProps<T>) => {
    return (
      <capri-lagoon style={{ display: "contents" }}>
        <Comp {...props} />
      </capri-lagoon>
    );
  };
}
