// packages/preact/src/island.server.jsx
import * as componentModule from "virtual:capri-component";

const { default: Component, options } = componentModule;

function Island({ children, ...props }) {
  const wrappedChildren = children && (
    <capri-children style={{ display: "contents" }}>{children}</capri-children>
  );

  const scriptContent = JSON.stringify({ props, options });
  return (
    <capri-island style={{ display: "contents" }}>
      <Component {...props}>{wrappedChildren}</Component>
      <script
        type="application/json"
        data-island="%COMPONENT_ID%"
        dangerouslySetInnerHTML={{ __html: scriptContent }}
      />
    </capri-island>
  );
}

export default Island;

// packages/solid/src/island.server.jsx
import { sharedConfig } from "solid-js";
import { NoHydration } from "solid-js/web";
import * as componentModule from "virtual:capri-component";
const { default: Component, options } = componentModule;

export function Hydration(props) {
  const c = sharedConfig.context;
  c.noHydrate = false;
  const children = props.children;
  c.noHydrate = true;
  return children;
}

export default function ComponentIsland({ children, ...props }) {
  const wrappedChildren = children && <NoHydration>{children}</NoHydration>;

  return (
    <capri-island style="display: contents">
      <Hydration>
        <Component {...props}>{wrappedChildren}</Component>
      </Hydration>
      <script
        type="application/json"
        data-island="%COMPONENT_ID%"
        innerHTML={JSON.stringify({ props, options })}
      />
    </capri-island>
  );
}
