// examples/vue/src/Counter.island.vue
<script setup lang="ts">
import { ref } from "vue";

interface Props {
  start?: number;
}
const { start = 0 } = defineProps<Props>();
const count = ref(start);
</script>

<template>
  <div data-testid="counter">
    <button @click="count--">-</button>
    <span>{{ count }}</span>
    <button @click="count++">+</button>
  </div>
</template>

<style scoped>
div {
  display: inline-flex;
  gap: 0.5em;
}
</style>

// templates/react/components/islands/counter.island.tsx
import { useState } from "react";

import { Button } from "../ui/button";

type Props = {
  start?: number;
};

export default function Counter({ start = 0 }: Props) {
  const [counter, setCounter] = useState(start);
  return (
    <div className="flex items-center gap-2">
      <Button onClick={() => setCounter((c) => c - 1)}>-</Button>
      <span>{counter}</span>
      <Button onClick={() => setCounter((c) => c + 1)}>+</Button>
    </div>
  );
}
